################################################################################
# Prefix settings
################################################################################
# Unbind the default Ctrl+b
unbind C-b

# Set the prefix to Ctrl-s
set -g prefix C-s
# Ensure that we can send Ctrl-s to other apps by pressing it twice
bind C-s send-prefix

################################################################################
# Key binding settings
################################################################################
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

################################################################################
# Plugin settings
################################################################################
# set -g @plugin_path '~/.config/tmux/plugins'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'

################################################################################
# Navigation settings
################################################################################
# Use Prefix + q to jump to the last active window (super fast toggling)
bind q last-window

################################################################################
# Other settings
################################################################################
# Start window/pane numbering at 1 (instead of 0) to match keyboard layout
set -g base-index 1
setw -g pane-base-index 1

set -g status-position top
# Refresh every 5 seconds instead of 1
set -g status-interval 5

# Enable RGB color focus-events (helps with redraw speed)
set -g focus-events on

# Set the default terminal inside tmux
set -g default-terminal "tmux-256color"
# This tells tmux that 'xterm-256color' (your host) supports RGB
set -as terminal-features ",xterm-256color:RGB"

# Enable mouse support (click tabs, resize panes)
set -g mouse on

# Eliminate the lag that makes Fish/Starship feel "heavy"
set -s escape-time 10
set -g focus-events on

################################################################################
# Catppuccing plugin settings
################################################################################
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# This installation method for the catppuccin plugin is recommended as TPM
# has some issues with name conflicts.
run '{{ tools_tmux_plugin_path }}/catppuccin/catppuccin.tmux'

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

################################################################################
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '{{ tools_tmux_plugin_path }}/tpm/tpm'
